controllers:
    resource: ../src/Controller/
    type: attribute

tasks:
    path: /
    controller: App\Controller\TaskController::index
    
task_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation
    
task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail
    
register:
    path: /registro
    controller: App\Controller\UserController::register
    
login:
    path: /login
    controller: App\Controller\UserController::login
    
logout:
    path: /logout